import os
import torch
import logging
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("ClipDetector")

class ClipAuthenticator:
    """
    Semantic Analysis layer using OpenAI's CLIP model.
    Performs Zero-Shot Classification to determine if the overall 'vibe' 
    and composition of the image aligns more with reality or AI-generation.
    Runs on CPU to preserve VRAM for the subsequent VLM layer.
    """

    def __init__(self,model_name:str = "openai/clip-vit-base-patch32"):
        self.model_name = model_name
        self.device = torch.device("cpu")

        self.ai_labels = [
            "a genuine authentic photograph captured by a camera, real life, unedited",
            "a fake synthetic image generated by artificial intelligence, midjourney, deepfake artifact"
        ]

        self.document_labels = [
            "a photo or scan of an argentinian receipt, invoice or payment voucher",
            "a photo of the front side of an argentinian identity card dni",
            "a photo of the back side of an argentinian identity card dni",
            "a photo of a debit card or credit card",
            "a screenshot of a homebanking or mobile banking app",
            "an unknown or unrelated document image"
        ]

        logger.info(f"Initializing ClipAuthenticator with model: {self.model_name} on {self.device}")

        try:
            self.processor = CLIPProcessor.from_pretrained(self.model_name)
            self.model = CLIPModel.from_pretrained(self.model_name, use_safetensors=True).to(self.device)
            self.model.eval() #freeze weights

            logger.info("OpenAI CLIP model loaded succesfully.")
        
        except Exception as e:
            logger.error(f"Failed to load the CLIP Model: {str(e)}")
            raise

    def _classify(self, image_path: str, labels: list[str]) -> tuple[list[float], int]:
        image = Image.open(image_path).convert("RGB")

        inputs = self.processor(
            text=labels,
            images=image,
            return_tensors="pt",
            padding=True
        ).to(self.device)

        with torch.no_grad():
            outputs = self.model(**inputs)
            logits_per_image = outputs.logits_per_image
            probabilities = logits_per_image.softmax(dim=1)[0]

        probabilities_list = [round(prob.item() * 100, 2) for prob in probabilities]
        top_index = int(torch.argmax(probabilities).item())
        return probabilities_list, top_index

    def analyze(self,image_path: str) -> dict:
        """
        Compares the image against generic real-vs-AI labels and returns probability scores.
        """
        try:
            probabilities, _ = self._classify(image_path, self.ai_labels)

            # Parse results (Index 0: Real, Index 1: AI)
            real_prob = probabilities[0]
            ai_prob = probabilities[1]

            is_ai = ai_prob > real_prob
            confidence = ai_prob if is_ai else real_prob
            classsification = "Artificial Intelligence" if is_ai else "Real Photograph"

            result = {
                "status":"success",
                "classification":classsification,
                "confidence_score":round(confidence, 2),
                "is_ai_generated":is_ai,
                "detailed_probabilities":{
                    "real_probability":round(real_prob, 2),
                    "ai_probability":round(ai_prob, 2)
                }
            }

            logger.info(f"CLIP Analysis Complete: AI={result['detailed_probabilities']['ai_probability']}%, Real={result['detailed_probabilities']['real_probability']}%")
            return result
        
        except Exception as e:
            logger.error(f"Error during CLIP analysis: {str(e)}")
            return {"status":"error", "message":str(e)}

    def classify_document_type(self, image_path: str) -> dict:
        """
        Zero-shot document routing for receipts, DNI front/back, cards and homebanking screenshots.
        """
        try:
            probabilities, top_index = self._classify(image_path, self.document_labels)
            top_label = self.document_labels[top_index]

            type_map = {
                0: "receipt",
                1: "dni_front",
                2: "dni_back",
                3: "card",
                4: "homebanking",
                5: "unknown",
            }

            document_type = type_map.get(top_index, "unknown")
            confidence = probabilities[top_index]

            result = {
                "status": "success",
                "document_type": document_type,
                "document_type_label": top_label,
                "document_type_confidence": confidence,
                "document_type_probabilities": {
                    "receipt": probabilities[0],
                    "dni_front": probabilities[1],
                    "dni_back": probabilities[2],
                    "card": probabilities[3],
                    "homebanking": probabilities[4],
                    "unknown": probabilities[5],
                },
            }

            logger.info(f"CLIP Document Type: {document_type} ({confidence}%)")
            return result

        except Exception as e:
            logger.error(f"Error during CLIP document type classification: {str(e)}")
            return {"status": "error", "message": str(e)}
        
if __name__== "__main__":

    authenticator = ClipAuthenticator()

    test_image_path = "test.jpg"
    
    result = authenticator.analyze(test_image_path)
    print(result) 