import os
import torch
import logging
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("ClipDetector")

class ClipAuthenticator:
    """
    Semantic Analysis layer using OpenAI's CLIP model.
    Performs Zero-Shot Classification to determine if the overall 'vibe' 
    and composition of the image aligns more with reality or AI-generation.
    Runs on CPU to preserve VRAM for the subsequent VLM layer.
    """

    def __init__(self,model_name:str = "openai/clip-vit-base-patch32"):
        self.model_name = model_name
        self.device = torch.device("cpu")

        self.labels = [
            "a genuine authentic photograph captured by a camera, real life, unedited",
            "a fake synthetic image generated by artificial intelligence, midjourney, deepfake artifact"
        ]

        logger.info(f"Initializing ClipAuthenticator with model: {self.model_name} on {self.device}")

        try:
            self.processor = CLIPProcessor.from_pretrained(self.model_name)
            self.model = CLIPModel.from_pretrained(self.model_name, use_safetensors=True).to(self.device)
            self.model.eval() #freeze weights

            logger.info("OpenAI CLIP model loaded succesfully.")
        
        except Exception as e:
            logger.error(f"Failed to load the CLIP Model: {str(e)}")
            raise

    def analyze(self,image_path: str) -> dict:
        """
        Compares the image against the predefined text labels and returns probability scores.
        """
        try:
            image = Image.open(image_path).convert("RGB")

            inputs = self.processor(
                text=self.labels,
                images=image,
                return_tensors="pt",
                padding=True
            ).to(self.device)

            with torch.no_grad():
                outputs = self.model(**inputs)

                # Calculate cosine similarity logits and apply softmax for probabilities
                logits_per_image = outputs.logits_per_image
                probabilities = logits_per_image.softmax(dim=1)[0]

            # Parse results (Index 0: Real, Index 1: AI)
            real_prob = probabilities[0].item()
            ai_prob = probabilities[1].item()

            is_ai = ai_prob > real_prob
            confidence = ai_prob if is_ai else real_prob
            classsification = "Artificial Intelligence" if is_ai else "Real Photograph"

            result = {
                "status":"success",
                "classification":classsification,
                "confidence_score":round(confidence * 100, 2),
                "is_ai_generated":is_ai,
                "detailed_probabilities":{
                    "real_probability":round(real_prob * 100, 2),
                    "ai_probability":round(ai_prob * 100, 2)
                }
            }

            logger.info(f"CLIP Analysis Complete: AI={result['detailed_probabilities']['ai_probability']}%, Real={result['detailed_probabilities']['real_probability']}%")
            return result
        
        except Exception as e:
            logger.error(f"Error during CLIP analysis: {str(e)}")
            return {"status":"error", "message":str(e)}
        
if __name__== "__main__":

    authenticator = ClipAuthenticator()

    test_image_path = "test.jpg"
    
    result = authenticator.analyze(test_image_path)
    print(result) 