import os
import torch
import logging
from PIL import Image
from transformers import AutoProcessor, Qwen2VLForConditionalGeneration, BitsAndBytesConfig

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("VlmExplainer")

class VlmExplanier:
    """
    Vision-Language Model (VLM) layer using Alibaba Cloud's Qwen2-VL-2B.
    Acts as the 'Detective' that explains logically WHY an image might be fake.
    Corporate-backed, natively integrated (no remote code execution required), 
    and utilizes 4-bit quantization to fit safely into a 4GB VRAM budget.
    """

    def __init__(self):
        self.model_id = "Qwen/Qwen2-VL-2B-Instruct"

        logger.info(f"Initializing VLM: {self.model_id}")

        try:
            self.processor = AutoProcessor.from_pretrained(self.model_id)

            bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_use_double_quant=True, bnb_4bit_quant_type="nf4",bnb_4bit_compute_dtype=torch.float16)

            self.model = Qwen2VLForConditionalGeneration.from_pretrained(self.model_id, quantization_config=bnb_config, device_map="auto")
            
            self.model.eval()
            logger.info("VLM Explainer loaded successfully.")

        except Exception as e:
            logger.error(f"Failed to laod the VLM model: {str(e)}")
            raise

    def analyze(self,image_path:str, prompt:str = None) -> dict:
        """
        Processes the image and asks the VLM to explain artificial anomalies.
        """
        if prompt is None:
            prompt = "Analyze this image carefully. Are there any physical impossibilities, weird artifacts, " \
            "asymmetrical details, or signs that it was generated by Artificial Intelligence or digitally altered? Explain your reasoning briefly."

        try:
            image = Image.open(image_path).convert("RGB")

            #Construct standard conversational dictionary format required by modern VLMs
            messages = [
                {
                    "role": "user",
                    "content": [
                        {"type": "image"},
                        {"type": "text", "text": prompt}
                    ]
                }
            ]

            # Convert human-readable dictionary into the specific robotic token syntax the model expects
            text_prompt = self.processor.apply_chat_template(messages,add_generation_prompt=True)

            # Convert text and images into PyTorch (pt) tensors and move them to GPU VRAM
            inputs = self.processor(
                text = [text_prompt],
                images = [image],
                padding=True,
                return_tensors="pt"
            ).to(self.model.device)

            # Disable gradient tracking (backpropagation history) during inference. 
            # This prevents catastrophic VRAM overflow and speeds up generation.
            with torch.no_grad():
                generated_ids = self.model.generate(**inputs, max_new_tokens=150)

                # Trim the original prompt from the output tensor to get pure generated text
                generated_ids_trimmed = [
                    out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids,generated_ids) #Genetared = [prompt + answer] -> [len(prompt:)] = [answer]
                ]

                # Decode token IDs back into human-readable English strings, hiding system tags
                explanation = self.processor.batch_decode(
                    generated_ids_trimmed,
                    skip_special_tokens=True,
                    clean_up_tokenization_spaces=False
                )[0]

                result = {
                    "status":"success",
                    "explanation":explanation.strip()
                }

                logger.info("VLM analysis complete")
                return result
            
        except Exception as e:
            logger.error(f"Error during VLM analysis {str(e)}")
            return {"status":"error", "message":str(e)}
        

if __name__ == "__main__":
    explainer = VlmExplanier()
    test_image_path = "test.jpg"

    result = explainer.analyze(test_image_path)
    print(result["explanation"])